#!/usr/bin/env bash
# Campsite default configuration
# Override in ~/.campsite/user/config.sh

# Days before a status/handoff file is considered stale
CAMPSITE_STALE_DAYS="${CAMPSITE_STALE_DAYS:-2}"

# Maximum directory levels to walk up when auto-detecting project
CAMPSITE_MAX_WALK_UP="${CAMPSITE_MAX_WALK_UP:-20}"

# Lock expiry in seconds (for orphan detection fallback)
CAMPSITE_LOCK_EXPIRY="${CAMPSITE_LOCK_EXPIRY:-86400}"

# Compiled context file header marker
CAMPSITE_HEADER_MARKER="<!-- Generated by campsite sync. Do not edit directly. -->"
