#!/usr/bin/env bash
# Campsite default configuration
# Override in ~/.campsite/user/config.sh

# Days before a status/handoff file is considered stale
CAMPSITE_STALE_DAYS="${CAMPSITE_STALE_DAYS:-2}"

# Maximum directory levels to walk up when auto-detecting project
CAMPSITE_MAX_WALK_UP="${CAMPSITE_MAX_WALK_UP:-20}"

# Lock expiry in seconds (for orphan detection fallback)
CAMPSITE_LOCK_EXPIRY="${CAMPSITE_LOCK_EXPIRY:-86400}"

# Compiled context file header marker
CAMPSITE_HEADER_MARKER="<!-- Generated by campsite sync. Do not edit directly. -->"

# Valid project phases (space-separated)
CAMPSITE_VALID_PHASES="${CAMPSITE_VALID_PHASES:-discovery building testing reviewing blocked deployed}"

# Source of truth files (space-separated, used for hash computation)
CAMPSITE_SOURCE_FILES="${CAMPSITE_SOURCE_FILES:-status.md handoff.md}"

# Number of recent decisions to include in compiled context
CAMPSITE_DECISION_COUNT="${CAMPSITE_DECISION_COUNT:-5}"

# Set to 1 to let `campsite save` attempt a checkpoint commit + push by default
CAMPSITE_SAVE_PUSH="${CAMPSITE_SAVE_PUSH:-0}"
