#!/usr/bin/env bats

load '../test_helper'

setup() {
    setup_temp_dir
    load_campsite_libs
    create_test_project
}

teardown() {
    teardown_temp_dir
}

# --- adapter_list tests ---

@test "adapter_list returns built-in adapters" {
    result="$(adapter_list)"
    
    [[ "$result" == *"claude"* ]]
    [[ "$result" == *"codex"* ]]
    [[ "$result" == *"cursor"* ]]
}

# --- adapter_load tests ---

@test "adapter_load sets ADAPTER variables" {
    adapter_load "claude"
    
    [[ "$ADAPTER_NAME" == "claude" ]]
    [[ "$ADAPTER_CONTEXT_FILE" == "CLAUDE.md" ]]
    [[ "$ADAPTER_COMMAND" == "claude" ]]
}

@test "adapter_load fails for unknown adapter" {
    run adapter_load "nonexistent"
    [[ "$status" -ne 0 ]]
}

# --- compile_context tests ---

@test "compile_context creates context file" {
    output_path="$(compile_context "$TEST_PROJECT" "claude")"
    
    [[ -f "$output_path" ]]
    [[ "$output_path" == "$TEST_PROJECT/CLAUDE.md" ]]
}

@test "compile_context includes campsite marker" {
    compile_context "$TEST_PROJECT" "claude"
    
    head -1 "$TEST_PROJECT/CLAUDE.md" | grep -q "campsite sync"
}

@test "compile_context includes status section" {
    compile_context "$TEST_PROJECT" "claude"
    
    grep -q "## Current Status" "$TEST_PROJECT/CLAUDE.md"
    grep -q "phase: building" "$TEST_PROJECT/CLAUDE.md"
}

@test "compile_context includes handoff section" {
    compile_context "$TEST_PROJECT" "claude"
    
    grep -q "## Next Action" "$TEST_PROJECT/CLAUDE.md"
    grep -q "task: implement tests" "$TEST_PROJECT/CLAUDE.md"
}

@test "compile_context includes session protocol" {
    compile_context "$TEST_PROJECT" "claude"
    
    grep -q "## Session Protocol" "$TEST_PROJECT/CLAUDE.md"
}

# --- compile_cleanup tests ---

@test "compile_cleanup removes compiled file" {
    compile_context "$TEST_PROJECT" "claude"
    [[ -f "$TEST_PROJECT/CLAUDE.md" ]]
    
    compile_cleanup "$TEST_PROJECT" "claude"
    [[ ! -f "$TEST_PROJECT/CLAUDE.md" ]]
}

@test "compile_cleanup ignores non-campsite files" {
    echo "# My custom CLAUDE.md" > "$TEST_PROJECT/CLAUDE.md"
    
    compile_cleanup "$TEST_PROJECT" "claude"
    
    # File should still exist (not generated by campsite)
    [[ -f "$TEST_PROJECT/CLAUDE.md" ]]
}

# --- compile_cleanup_all tests ---

@test "compile_cleanup_all removes all compiled files" {
    compile_context "$TEST_PROJECT" "claude"
    compile_context "$TEST_PROJECT" "codex"
    
    [[ -f "$TEST_PROJECT/CLAUDE.md" ]]
    [[ -f "$TEST_PROJECT/AGENTS.md" ]]
    
    compile_cleanup_all "$TEST_PROJECT"
    
    [[ ! -f "$TEST_PROJECT/CLAUDE.md" ]]
    [[ ! -f "$TEST_PROJECT/AGENTS.md" ]]
}
